package com.liusure.springboot.dao;

import com.liusure.springboot.entity.CspOrder;
import com.liusure.springboot.entity.CspOrderExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface CspOrderMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table csp_order
     *
     * @mbggenerated
     */
    int countByExample(CspOrderExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table csp_order
     *
     * @mbggenerated
     */
    int deleteByExample(CspOrderExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table csp_order
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table csp_order
     *
     * @mbggenerated
     */
    int insert(CspOrder record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table csp_order
     *
     * @mbggenerated
     */
    int insertSelective(CspOrder record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table csp_order
     *
     * @mbggenerated
     */
    List<CspOrder> selectByExample(CspOrderExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table csp_order
     *
     * @mbggenerated
     */
    CspOrder selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table csp_order
     *
     * @mbggenerated
     */
    int updateByExampleSelective(@Param("record") CspOrder record, @Param("example") CspOrderExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table csp_order
     *
     * @mbggenerated
     */
    int updateByExample(@Param("record") CspOrder record, @Param("example") CspOrderExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table csp_order
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(CspOrder record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table csp_order
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(CspOrder record);
}