package com.liusure.springboot.dao;

import com.liusure.springboot.entity.InnerOrg;
import com.liusure.springboot.entity.InnerOrgExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface InnerOrgMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table inner_org
     *
     * @mbggenerated
     */
    int countByExample(InnerOrgExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table inner_org
     *
     * @mbggenerated
     */
    int deleteByExample(InnerOrgExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table inner_org
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(String innerOrgId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table inner_org
     *
     * @mbggenerated
     */
    int insert(InnerOrg record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table inner_org
     *
     * @mbggenerated
     */
    int insertSelective(InnerOrg record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table inner_org
     *
     * @mbggenerated
     */
    List<InnerOrg> selectByExample(InnerOrgExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table inner_org
     *
     * @mbggenerated
     */
    InnerOrg selectByPrimaryKey(String innerOrgId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table inner_org
     *
     * @mbggenerated
     */
    int updateByExampleSelective(@Param("record") InnerOrg record, @Param("example") InnerOrgExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table inner_org
     *
     * @mbggenerated
     */
    int updateByExample(@Param("record") InnerOrg record, @Param("example") InnerOrgExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table inner_org
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(InnerOrg record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table inner_org
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(InnerOrg record);
}