package com.liusure.springboot.entity;

import java.util.Date;

public class InnerOrg {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column inner_org.inner_org_id
     *
     * @mbggenerated
     */
    private String innerOrgId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column inner_org.org_code
     *
     * @mbggenerated
     */
    private String orgCode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column inner_org.vip_identity_id
     *
     * @mbggenerated
     */
    private Byte vipIdentityId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column inner_org.contact_person
     *
     * @mbggenerated
     */
    private String contactPerson;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column inner_org.tel
     *
     * @mbggenerated
     */
    private String tel;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column inner_org.address
     *
     * @mbggenerated
     */
    private String address;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column inner_org.location_id
     *
     * @mbggenerated
     */
    private String locationId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column inner_org.remarks
     *
     * @mbggenerated
     */
    private String remarks;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column inner_org.files_path
     *
     * @mbggenerated
     */
    private String filesPath;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column inner_org.creater_id
     *
     * @mbggenerated
     */
    private String createrId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column inner_org.create_time
     *
     * @mbggenerated
     */
    private Date createTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column inner_org.update_time
     *
     * @mbggenerated
     */
    private Date updateTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column inner_org.org_name
     *
     * @mbggenerated
     */
    private String orgName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column inner_org.mobile
     *
     * @mbggenerated
     */
    private String mobile;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column inner_org.org_tag
     *
     * @mbggenerated
     */
    private Byte orgTag;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column inner_org.bank_account
     *
     * @mbggenerated
     */
    private String bankAccount;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column inner_org.bank_account_identity
     *
     * @mbggenerated
     */
    private String bankAccountIdentity;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column inner_org.bank_location
     *
     * @mbggenerated
     */
    private String bankLocation;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column inner_org.bank_name
     *
     * @mbggenerated
     */
    private String bankName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column inner_org.bank_branch_name
     *
     * @mbggenerated
     */
    private String bankBranchName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column inner_org.bank_card_number
     *
     * @mbggenerated
     */
    private String bankCardNumber;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column inner_org.status
     *
     * @mbggenerated
     */
    private Byte status;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column inner_org.hub_level
     *
     * @mbggenerated
     */
    private Byte hubLevel;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column inner_org.email
     *
     * @mbggenerated
     */
    private String email;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column inner_org.longitude
     *
     * @mbggenerated
     */
    private Double longitude;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column inner_org.latitude
     *
     * @mbggenerated
     */
    private Double latitude;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column inner_org.latest_time
     *
     * @mbggenerated
     */
    private Date latestTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column inner_org.short_hub_name
     *
     * @mbggenerated
     */
    private String shortHubName;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column inner_org.inner_org_id
     *
     * @return the value of inner_org.inner_org_id
     *
     * @mbggenerated
     */
    public String getInnerOrgId() {
        return innerOrgId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column inner_org.inner_org_id
     *
     * @param innerOrgId the value for inner_org.inner_org_id
     *
     * @mbggenerated
     */
    public void setInnerOrgId(String innerOrgId) {
        this.innerOrgId = innerOrgId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column inner_org.org_code
     *
     * @return the value of inner_org.org_code
     *
     * @mbggenerated
     */
    public String getOrgCode() {
        return orgCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column inner_org.org_code
     *
     * @param orgCode the value for inner_org.org_code
     *
     * @mbggenerated
     */
    public void setOrgCode(String orgCode) {
        this.orgCode = orgCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column inner_org.vip_identity_id
     *
     * @return the value of inner_org.vip_identity_id
     *
     * @mbggenerated
     */
    public Byte getVipIdentityId() {
        return vipIdentityId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column inner_org.vip_identity_id
     *
     * @param vipIdentityId the value for inner_org.vip_identity_id
     *
     * @mbggenerated
     */
    public void setVipIdentityId(Byte vipIdentityId) {
        this.vipIdentityId = vipIdentityId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column inner_org.contact_person
     *
     * @return the value of inner_org.contact_person
     *
     * @mbggenerated
     */
    public String getContactPerson() {
        return contactPerson;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column inner_org.contact_person
     *
     * @param contactPerson the value for inner_org.contact_person
     *
     * @mbggenerated
     */
    public void setContactPerson(String contactPerson) {
        this.contactPerson = contactPerson;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column inner_org.tel
     *
     * @return the value of inner_org.tel
     *
     * @mbggenerated
     */
    public String getTel() {
        return tel;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column inner_org.tel
     *
     * @param tel the value for inner_org.tel
     *
     * @mbggenerated
     */
    public void setTel(String tel) {
        this.tel = tel;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column inner_org.address
     *
     * @return the value of inner_org.address
     *
     * @mbggenerated
     */
    public String getAddress() {
        return address;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column inner_org.address
     *
     * @param address the value for inner_org.address
     *
     * @mbggenerated
     */
    public void setAddress(String address) {
        this.address = address;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column inner_org.location_id
     *
     * @return the value of inner_org.location_id
     *
     * @mbggenerated
     */
    public String getLocationId() {
        return locationId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column inner_org.location_id
     *
     * @param locationId the value for inner_org.location_id
     *
     * @mbggenerated
     */
    public void setLocationId(String locationId) {
        this.locationId = locationId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column inner_org.remarks
     *
     * @return the value of inner_org.remarks
     *
     * @mbggenerated
     */
    public String getRemarks() {
        return remarks;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column inner_org.remarks
     *
     * @param remarks the value for inner_org.remarks
     *
     * @mbggenerated
     */
    public void setRemarks(String remarks) {
        this.remarks = remarks;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column inner_org.files_path
     *
     * @return the value of inner_org.files_path
     *
     * @mbggenerated
     */
    public String getFilesPath() {
        return filesPath;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column inner_org.files_path
     *
     * @param filesPath the value for inner_org.files_path
     *
     * @mbggenerated
     */
    public void setFilesPath(String filesPath) {
        this.filesPath = filesPath;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column inner_org.creater_id
     *
     * @return the value of inner_org.creater_id
     *
     * @mbggenerated
     */
    public String getCreaterId() {
        return createrId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column inner_org.creater_id
     *
     * @param createrId the value for inner_org.creater_id
     *
     * @mbggenerated
     */
    public void setCreaterId(String createrId) {
        this.createrId = createrId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column inner_org.create_time
     *
     * @return the value of inner_org.create_time
     *
     * @mbggenerated
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column inner_org.create_time
     *
     * @param createTime the value for inner_org.create_time
     *
     * @mbggenerated
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column inner_org.update_time
     *
     * @return the value of inner_org.update_time
     *
     * @mbggenerated
     */
    public Date getUpdateTime() {
        return updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column inner_org.update_time
     *
     * @param updateTime the value for inner_org.update_time
     *
     * @mbggenerated
     */
    public void setUpdateTime(Date updateTime) {
        this.updateTime = updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column inner_org.org_name
     *
     * @return the value of inner_org.org_name
     *
     * @mbggenerated
     */
    public String getOrgName() {
        return orgName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column inner_org.org_name
     *
     * @param orgName the value for inner_org.org_name
     *
     * @mbggenerated
     */
    public void setOrgName(String orgName) {
        this.orgName = orgName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column inner_org.mobile
     *
     * @return the value of inner_org.mobile
     *
     * @mbggenerated
     */
    public String getMobile() {
        return mobile;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column inner_org.mobile
     *
     * @param mobile the value for inner_org.mobile
     *
     * @mbggenerated
     */
    public void setMobile(String mobile) {
        this.mobile = mobile;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column inner_org.org_tag
     *
     * @return the value of inner_org.org_tag
     *
     * @mbggenerated
     */
    public Byte getOrgTag() {
        return orgTag;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column inner_org.org_tag
     *
     * @param orgTag the value for inner_org.org_tag
     *
     * @mbggenerated
     */
    public void setOrgTag(Byte orgTag) {
        this.orgTag = orgTag;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column inner_org.bank_account
     *
     * @return the value of inner_org.bank_account
     *
     * @mbggenerated
     */
    public String getBankAccount() {
        return bankAccount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column inner_org.bank_account
     *
     * @param bankAccount the value for inner_org.bank_account
     *
     * @mbggenerated
     */
    public void setBankAccount(String bankAccount) {
        this.bankAccount = bankAccount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column inner_org.bank_account_identity
     *
     * @return the value of inner_org.bank_account_identity
     *
     * @mbggenerated
     */
    public String getBankAccountIdentity() {
        return bankAccountIdentity;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column inner_org.bank_account_identity
     *
     * @param bankAccountIdentity the value for inner_org.bank_account_identity
     *
     * @mbggenerated
     */
    public void setBankAccountIdentity(String bankAccountIdentity) {
        this.bankAccountIdentity = bankAccountIdentity;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column inner_org.bank_location
     *
     * @return the value of inner_org.bank_location
     *
     * @mbggenerated
     */
    public String getBankLocation() {
        return bankLocation;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column inner_org.bank_location
     *
     * @param bankLocation the value for inner_org.bank_location
     *
     * @mbggenerated
     */
    public void setBankLocation(String bankLocation) {
        this.bankLocation = bankLocation;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column inner_org.bank_name
     *
     * @return the value of inner_org.bank_name
     *
     * @mbggenerated
     */
    public String getBankName() {
        return bankName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column inner_org.bank_name
     *
     * @param bankName the value for inner_org.bank_name
     *
     * @mbggenerated
     */
    public void setBankName(String bankName) {
        this.bankName = bankName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column inner_org.bank_branch_name
     *
     * @return the value of inner_org.bank_branch_name
     *
     * @mbggenerated
     */
    public String getBankBranchName() {
        return bankBranchName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column inner_org.bank_branch_name
     *
     * @param bankBranchName the value for inner_org.bank_branch_name
     *
     * @mbggenerated
     */
    public void setBankBranchName(String bankBranchName) {
        this.bankBranchName = bankBranchName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column inner_org.bank_card_number
     *
     * @return the value of inner_org.bank_card_number
     *
     * @mbggenerated
     */
    public String getBankCardNumber() {
        return bankCardNumber;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column inner_org.bank_card_number
     *
     * @param bankCardNumber the value for inner_org.bank_card_number
     *
     * @mbggenerated
     */
    public void setBankCardNumber(String bankCardNumber) {
        this.bankCardNumber = bankCardNumber;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column inner_org.status
     *
     * @return the value of inner_org.status
     *
     * @mbggenerated
     */
    public Byte getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column inner_org.status
     *
     * @param status the value for inner_org.status
     *
     * @mbggenerated
     */
    public void setStatus(Byte status) {
        this.status = status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column inner_org.hub_level
     *
     * @return the value of inner_org.hub_level
     *
     * @mbggenerated
     */
    public Byte getHubLevel() {
        return hubLevel;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column inner_org.hub_level
     *
     * @param hubLevel the value for inner_org.hub_level
     *
     * @mbggenerated
     */
    public void setHubLevel(Byte hubLevel) {
        this.hubLevel = hubLevel;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column inner_org.email
     *
     * @return the value of inner_org.email
     *
     * @mbggenerated
     */
    public String getEmail() {
        return email;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column inner_org.email
     *
     * @param email the value for inner_org.email
     *
     * @mbggenerated
     */
    public void setEmail(String email) {
        this.email = email;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column inner_org.longitude
     *
     * @return the value of inner_org.longitude
     *
     * @mbggenerated
     */
    public Double getLongitude() {
        return longitude;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column inner_org.longitude
     *
     * @param longitude the value for inner_org.longitude
     *
     * @mbggenerated
     */
    public void setLongitude(Double longitude) {
        this.longitude = longitude;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column inner_org.latitude
     *
     * @return the value of inner_org.latitude
     *
     * @mbggenerated
     */
    public Double getLatitude() {
        return latitude;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column inner_org.latitude
     *
     * @param latitude the value for inner_org.latitude
     *
     * @mbggenerated
     */
    public void setLatitude(Double latitude) {
        this.latitude = latitude;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column inner_org.latest_time
     *
     * @return the value of inner_org.latest_time
     *
     * @mbggenerated
     */
    public Date getLatestTime() {
        return latestTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column inner_org.latest_time
     *
     * @param latestTime the value for inner_org.latest_time
     *
     * @mbggenerated
     */
    public void setLatestTime(Date latestTime) {
        this.latestTime = latestTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column inner_org.short_hub_name
     *
     * @return the value of inner_org.short_hub_name
     *
     * @mbggenerated
     */
    public String getShortHubName() {
        return shortHubName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column inner_org.short_hub_name
     *
     * @param shortHubName the value for inner_org.short_hub_name
     *
     * @mbggenerated
     */
    public void setShortHubName(String shortHubName) {
        this.shortHubName = shortHubName;
    }
}